name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of grpcio"
        type: string
        required: true
        default: "1.49.0"

jobs:
  build_wheels:
    name: Build grpcio==${{ github.event.inputs.version }} wheels on ${{ matrix.os }}, for Python ${{ matrix.python_build_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "macOS-12" ]
        python_build_version: [ "cp310", "cp311" ]

    steps:
      # Used to host cibuildwheel
      - uses: actions/setup-python@v3
      
      - name: Download grpcio tarball
        run: |
          pip download --no-binary grpcio grpcio==${{ github.event.inputs.version }}
          tar xf *.tar.gz
          
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.9.0

      - name: Build wheels
        run: |
          cd grpcio-*/
          python -m cibuildwheel --output-dir ../wheelhouse
        env:
          CIBW_ARCHS_MACOS: "arm64"
          CIBW_TEST_SKIP: "*_arm64"
          CIBW_BUILD: "${{ matrix.python_build_version }}-macosx_arm64"
          CIBW_BUILD_FRONTEND: pip
          CIBW_ENVIRONMENT_MACOS: "GRPC_PYTHON_BUILD_WITH_CYTHON=1"
          CIBW_BEFORE_BUILD: "pip install -r requirements.txt"

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{ github.event.inputs.version }}
          path: ./wheelhouse/*.whl
